---
- name: Deploy configs
  hosts: all
  tasks:
    - name: Deploy config via eAPI
      arista.eos.eos_config:
        src: "{{ lookup( 'env', 'PWD' ) }}/backup_configs/{{ inventory_hostname }}.cfg"
        save_when: always
        # backup: true
        # backup_options:
        #   filename: "{{ inventory_hostname }}.cfg "
        #   dir_path: "{{ lookup('env','PWD') }}/backup_configs/"